facturaelectronica/protected/modules/facturas/controllers/ProformaController.php
<?php

class ProformaController extends Controller 
{ 
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','prof','prof2','prof3','prof4','prof5','prof6','prof7','prof8','prof12','prof14','prof15','prof16','prof17','prof18'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
{
		Yii::import("application.modules.registro.models.Productos", true); 
		Yii::import("application.modules.registro.models.Identificacion", true); 
		Yii::import("application.modules.registro.models.TipoCodigo", true); 
		Yii::import("application.modules.registro.models.TablaProducto",true);

        $estadoListData = CHtml::listData(Provincia::model()->findAll(),  'id_provincia','provincia');
   
		$model=new Proforma;
		$modelPro=new Productos;
		$modelClie=new Clientes;
		$modelIde=new Identificacion;
		$tablaProducto=new TablaProducto;
		$TablaProductoProforma=new TablaProductoProforma;

	    $clientes=ListaImpuesto::model()->findAll();
	    $clientes2=Clientes::model()->findAll();
	    $clientes3=Productos::model()->findAll();
		
  		$modelClie->unsetAttributes();  // clear any default values
		if(isset($_GET['Clientes']))
			$modelClie->attributes=$_GET['Clientes']; 
		
		$modelPro->unsetAttributes();  // clear any default values
		if(isset($_GET['Productos']))
			$modelPro->attributes=$_GET['Productos'];
			
		
		if(isset($_POST['Proforma']))
		{	
			//tabular productos
			$tablaProducto->attributes=$_POST['TablaProducto'];
			$tablaProducto->codigo_produc=$_POST['TablaProducto']['codigo_produc'];

			$arrayid=explode(",", $_POST['TablaProducto']['id_producto']); 
			$arraycodigo=explode(",", $_POST['TablaProducto']['codigo_produc']); 
			$arraynombre=explode(",", $_POST['TablaProducto']['nombre_produc']);
			$arraytotal=explode(",", $_POST['TablaProducto']['total']);
			$arraycantidad=explode(",", $_POST['TablaProducto']['cantidad']);
			$arraycosto=explode(",", $_POST['TablaProducto']['costo_producto']);
			$arraydescuento=explode(",", $_POST['TablaProducto']['descuento']);
			$arrayiv=explode(",", $_POST['TablaProducto']['iv']);
			//modales tabulares
			$arraytipoexoneracion=explode(",", $_POST['TablaProducto']['tipoexoneracion']);
			$arraydocumentoexo=explode(",", $_POST['TablaProducto']['documentoexo']);
			$arrayinstituexo=explode(",", $_POST['TablaProducto']['instituexo']);
			$arrayfechaexo=explode(",", $_POST['TablaProducto']['fechaexo']);
			$arrayimpuestoexo=explode(",", $_POST['TablaProducto']['impuestoexo']);
			$arrayporcentajeexo=explode(",", $_POST['TablaProducto']['porcentajeexo']);

			//proforma

			$model->attributes=$_POST['Proforma'];
			
			$valido=$model->validate();
			if($valido){
			if( $model->total2!=""){
			$model->save();

			foreach ($arraycodigo as $key => $value) {
              		$TablaProductoProforma=new TablaProductoProforma;
      				$TablaProductoProforma->id_producto=$arrayid[$key];
              		$TablaProductoProforma->id_factura=$model->id_proforma;
              		$TablaProductoProforma->codigo_produc=$arraycodigo[$key];
              		$TablaProductoProforma->nombre_produc=$arraynombre[$key];
              		$TablaProductoProforma->total=$arraytotal[$key];
              		$TablaProductoProforma->cantidad=$arraycantidad[$key];
              		$TablaProductoProforma->costo_producto=$arraycosto[$key];
              		$TablaProductoProforma->descuento=$arraydescuento[$key]; 
              		$TablaProductoProforma->iv=$arrayiv[$key]; 
              		$TablaProductoProforma->id_cliente=$model->id_cliente;
              		//modal
              		$TablaProductoProforma->tipoexoneracion=$arraytipoexoneracion[$key];
              		$TablaProductoProforma->documentoexo=$arraydocumentoexo[$key];
              		$TablaProductoProforma->instituexo=$arrayinstituexo[$key];
              		$TablaProductoProforma->fechaexo=$arrayfechaexo[$key];
              		$TablaProductoProforma->impuestoexo=$arrayimpuestoexo[$key];
              		$TablaProductoProforma->porcentajeexo=$arrayporcentajeexo[$key];

              		$TablaProductoProforma->save(false);             		
              	}

          $this->redirect(array('create&guard=1')); 
          }				

				
			}
		}

		if(isset($_POST['Productos'])) 
		{
			$modelPro->attributes=$_POST['Productos'];
			
			$valido=$modelPro->validate();
		    
			if($valido){
               
				
				if($modelPro->precio_finalc_id!=0){
					$modelPro->save();
					$this->redirect(array('//registro/productos/admin'));
				}

				
			}
			
		}
	if(isset($_POST['Clientes']))
		{
			$modelClie->attributes=$_POST['Clientes'];
			$valido=$modelClie->validate();
		    
			if($valido){
               
				$modelClie->save();
				Yii::app()->user->setFlash('success','Registro Exitoso');
				if($modelClie->identificacion!=""){
				$this->redirect(array('//registro/clientes/admin'));
				}
			}
			
		}
		/*if(isset($_POST['TablaProducto']))
		{
			

			$tablaProducto->attributes=$_POST['TablaProducto'];
			$valido=$tablaProducto->validate();
		}*/
		$this->render('create',array(
			'model'=>$model,'modelPro'=>$modelPro,'modelClie'=>$modelClie,'clientes'=>$clientes,'clientes2'=>$clientes2,'clientes3'=>$clientes3,'tablaProducto'=>$tablaProducto,
		'estadoListData'=>$estadoListData)); 

	}
 
	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		//var_dump($model);exit();
		Yii::import("application.modules.registro.models.Productos", true); 
		Yii::import("application.modules.registro.models.Identificacion", true); 
		Yii::import("application.modules.registro.models.TipoCodigo", true); 
		Yii::import("application.modules.registro.models.TablaProducto",true);

        $estadoListData = CHtml::listData(Provincia::model()->findAll(),  'id_provincia','provincia');
   
		$modelPro=new Productos;
		$modelClie=new Clientes;
		$modelIde=new Identificacion;
		$tablaProducto=new TablaProducto;
		$TablaProductoProforma=new TablaProductoProforma;

	    $clientes=ListaImpuesto::model()->findAll();
	    $clientes2=Clientes::model()->findAll();
	    $clientes3=Productos::model()->findAll();
		
  		$modelClie->unsetAttributes();  // clear any default values
		if(isset($_GET['Clientes']))
			$modelClie->attributes=$_GET['Clientes']; 
		
		$modelPro->unsetAttributes();  // clear any default values
		if(isset($_GET['Productos']))
			$modelPro->attributes=$_GET['Productos'];
			
		
		if(isset($_POST['Proforma']))
		{	
			//tabular productos
			$tablaProducto->attributes=$_POST['TablaProducto'];
			$tablaProducto->codigo_produc=$_POST['TablaProducto']['codigo_produc'];

			$arrayid=explode(",", $_POST['TablaProducto']['id_producto']); 
			$arraycodigo=explode(",", $_POST['TablaProducto']['codigo_produc']); 
			$arraynombre=explode(",", $_POST['TablaProducto']['nombre_produc']);
			$arraytotal=explode(",", $_POST['TablaProducto']['total']);
			$arraycantidad=explode(",", $_POST['TablaProducto']['cantidad']);
			$arraycosto=explode(",", $_POST['TablaProducto']['costo_producto']);
			$arraydescuento=explode(",", $_POST['TablaProducto']['descuento']);
			$arrayiv=explode(",", $_POST['TablaProducto']['iv']);
			//modales tabulares
			$arraytipoexoneracion=explode(",", $_POST['TablaProducto']['tipoexoneracion']);
			$arraydocumentoexo=explode(",", $_POST['TablaProducto']['documentoexo']);
			$arrayinstituexo=explode(",", $_POST['TablaProducto']['instituexo']);
			$arrayfechaexo=explode(",", $_POST['TablaProducto']['fechaexo']);
			$arrayimpuestoexo=explode(",", $_POST['TablaProducto']['impuestoexo']);
			$arrayporcentajeexo=explode(",", $_POST['TablaProducto']['porcentajeexo']);

			//proforma

			$model->attributes=$_POST['Proforma'];
			
			$valido=$model->validate();
			if($valido){
			if( $model->total2!=""){
			$model->save();  
			$TablaProforma=TablaProductoProforma::model()->findAll('id_factura='.$model->id_proforma);
			foreach ($TablaProforma as $key => $value) {
				$TablaProforma[$key]->delete();
			}

			foreach ($arraycodigo as $key => $value) {
              		$TablaProductoProforma=new TablaProductoProforma;
      				$TablaProductoProforma->id_producto=$arrayid[$key];
              		$TablaProductoProforma->id_factura=$model->id_proforma;
              		$TablaProductoProforma->codigo_produc=$arraycodigo[$key];
              		$TablaProductoProforma->nombre_produc=$arraynombre[$key];
              		$TablaProductoProforma->total=$arraytotal[$key];

facturaelectronica/protected/modules/facturas/views/proforma/Prof.php
<?php 
$lineas=count($productos);

$header='

	<h3 align="center">Proforma de Prueba</h3>		
';
		

 $html='<br>
 <table width="100%">

 <tr ><td style="font-size:10px;" align="center" > '.$contribuyente->nombre.'</td></tr>
 <tr ><td align="center" style="font-size:13px;"  > '.$contribuyente->identificacion.'</td></tr>
<tr ><td align="center" style="font-size:13px;" > <b>Teléfono:</b> (506) '.$contribuyente->telefono.' </td></tr>
<tr ><td align="center" style="font-size:13px;" > '.$contribuyente->correo.' </td></tr>
</table>
<br>
<table>
<tr>
<td><b style="font-size:12px;" align="center">Factura Electrónica</b></td>
<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>N° #</b>'.$proforma->id_proforma;
$html.='</td></tr><tr>
<td colspan="2"><b style="font-size:12px;" align="center">Fecha: </b>  '.$proforma->fecha;
$html.=' </td></tr><tr>
<td colspan="2" ><b style="font-size:12px;" align="center">Moneda:</b> '.$moneda->aka;
$html.='
		</td></tr>
		<tr>';
if($cliente->identificacion!=0){
$html.='<td colspan="2"><b style="font-size:12px;" align="center">Cédula:</b> '.$cliente->identificacion;
$html.='
		</td></tr><tr>
		<td colspan="2"><b style="font-size:12px;" align="center">Nombre:</b> '.$cliente->clientes;
$html.=' </td></tr><tr>
<td colspan="2"><b style="font-size:12px;" align="center">Teléfono: </b>'.$cliente->telefono;
$html.='
</td>
</tr>
<tr>
<td colspan="2"><b style="font-size:12px;" align="center">Dirección:</b> '.$cliente->direccion;
$html.='</tr>';}
$html.='</tr>

</table>';
if($proforma->efec_monto>0&&$proforma->trs_monto!=0){
	$html.='<p><b style="font-size:12px;" align="center">Método de Pago:</b> Efectivo y Transferencia</p>';
}elseif($proforma->efec_monto>0&&$proforma->ch_monto!=0){
$html.='<p><b style="font-size:12px;" align="center">Método de Pago:</b> Efectivo y Cheque</p>';	
}elseif($proforma->efec_monto>0&&$proforma->tj_monto!=0){
$html.='<p><b style="font-size:12px;" align="center">Método de Pago:</b> Efectivo y tarjeta</p>';	
}elseif($proforma->trs_monto>0&&$proforma->ch_monto!=0){
$html.='<p><b style="font-size:12px;" align="center">Método de Pago:</b> Transferencia y Cheque</p>';	
}elseif($proforma->trs_monto>0&&$proforma->tj_monto!=0){
$html.='<p><b style="font-size:12px;" align="center">Método de Pago:</b> Transferencia y tarjeta</p>';	
}elseif($proforma->ch_monto>0&&$proforma->tj_monto!=0){
$html.='<p><b style="font-size:12px;" align="center">Método de Pago:</b>Cheque y Tarjeta</p>';
}elseif($proforma->tj_monto!=0){
$html.='<p><b style="font-size:12px;" align="center">Método de Pago:</b> Tarjeta</p>';
}elseif($proforma->ch_monto!=0){
	$html.='<p><b style="font-size:12px;" align="center">Método de Pago:</b> Cheque</p>';
}elseif($proforma->trs_monto!=0){
	$html.='<p><b style="font-size:12px;" align="center">Método de Pago:</b> Transferencia</p>';
}elseif($proforma->efec_monto!=0){
	$html.='<p><b style="font-size:12px;" align="center">Método de Pago:</b> Efectivo</p>';
}
        $html.='<table class="detail-view2"  cellpadding="1" cellspacing="1" width="100%" border="0">
            <tr class="principal" style="font-size:1em;" >
				
                 <td class="principal" style="font-size:1,7em;" width="25%" align="right"><b>&nbsp;Artículo </b></td>
                <td class="principal" style="font-size:1,7em;" width="20%" align="right"><b>&nbsp; Cant. </b></td>              
                <td class="principal" style="font-size:1,7em;" width="20%" align="right"><b>&nbsp; Precio</b></td>
                <td class="principal" style="font-size:1,7em;" width="20%" align="right"><b>&nbsp; IVI </b></td>
                <td class="principal" style="font-size:1,7em;" width="20%" align="right"><b>&nbsp; TOTAL</b></td>
                </tr>';
                $totalf=0;
                $iva=0;
                $subt=0;
                $desc=0;
                $vuelto=0;
                foreach ($productos as $key => $value) {
                	
               
                
               $html.='<tr>
                <td class="principal" style="font-size:1,7em;" align="right" width="25%">'.$value->nombre_produc;
$html.='
                </td>
                <td class="principal" style="font-size:1,7em;" align="right" width="25%">'.$value->cantidad;
$html.='
                </td>
                <td class="principal" style="font-size:1,7em;" align="right" width="25%">'.$value->costo_producto;
$html.='
                </td>
                <td class="principal" style="font-size:1,7em;" align="right" width="25%">'.$value->iv;
$html.='</td>
                <td class="principal" style="font-size:1,7em;" align="right" width="25%">'.$value->total;
$html.='
                </td>
                </tr>';
                $totalf+=$value->total;
                $iv=(($value->total*$value->iv)/100);
                $iva+=$iv;
                $subt+=$value->costo_producto*$value->cantidad;
                $vuelto+=$proforma->vuelto;
                $pagado+=$proforma->total_completo;
               
}
$totalfin+=$totalf+$iva;

$html.='
                </table><br>';

$html.='
		<table align="center"><tr>
		<th><b>&nbsp;Subtotal </b></th>
		</tr>
		<td>'.$subt;
$html.='</td></tr><tr>
		<th><b>&nbsp;Descuento </b></th>
		</tr>
		<td>'.$proforma->id_descuento;
		$iv=
$html.='</td></tr><tr>
		<th><b>&nbsp;I.V </b></th>
		</tr>
		<td>'.$iva;

$html.='</td></tr><tr>
		<th><b>&nbsp;Otros Imp. </b></th>
		</tr>
		<td>0
</td></tr><tr>
		<th><b>&nbsp;Total. </b></th>
		</tr>
		<td>'.$totalfin;
$html.='</td></tr><tr>
		<th><b>&nbsp;Pagado. </b></th>
		</tr>
		<td>'.$proforma->total_completo;
$html.='</td></tr><tr>
		<th><b>&nbsp;Vuelto. </b></th>
		</tr>
		<td>'.$proforma->vuelto;
$html.='</td></tr>
		</table>

                
                
                ';
$html.='
<div>
<p>Clave:</p>

<p>Autorizada mediante resolución
Nº DGT-R-48-2016 del 7 de octubre de 2016
</p>
</div>

';           




	
 
 $footer='';

?>
<?php 
	if($vista == 1)
	{
		echo '<div class="form">';
		?>
<div class="printable">
		 		<?php echo $header.$html.$footer; ?>
		 	</div>
		 	<!-- Cierre de la clase para imprimir  -->
		
		<div style ="align:center; position:fixed;bottom:0;">
        <table>
              <tr>
              	<td>
	
	
		<?php 
						$this->widget('zii.widgets.jui.CJuiButton', array(
		                            'cssFile'=> Yii::app()->request->baseUrl.'/css/jquery.css',
					    			'buttonType'=>'button',
		                            'name'=>'Imprimir',
								    'caption'=>'Imprimir',
								    'onclick'=>'js:function(){$(".printable").print();}',
									
		
					));?>
					</td>
	
			</tr>
		</table>
        </div>
        <?php 
        echo '</div>';
	}
	else
	{
		//echo '<div class="form">';
		$pdf = Yii::createComponent('application.extensions.mpdf53.mpdf');
		$lineas=($lineas*4.3)+205;
		//var_dump($lineas);exit();
		
		
		$mpdf=new mPDF('c',array(100,$lineas),10,10,10,8,15,9);
		$mpdf->SetHTMLHeader($header);
		$mpdf->SetHTMLFooter($footer);
		$mpdf->SetTitle('Proforma N#'.$Proforma->Proforma);
		$mpdf->SetFooter(' {DATE j/m/Y}|Pg{PAGENO}/{nbpg}|'.$cliente->clientes.'');
		$mpdf->WriteHTML($html);
		$mpdf->Output('Factura.pdf','I');
		//echo '</div>';
		exit;
	}
	
?>

facturaelectronica/protected/modules/facturas/views/proforma/_search.php
<?php
/* @var $this FacturaController */
/* @var $model Factura */
/* @var $form CActiveForm */
?>
		<div class="wide form">
		<?php $form=$this->beginWidget('CActiveForm', array(
			'action'=>Yii::app()->createUrl($this->route),
			'method'=>'get',
		)); ?>
		<div class="col col-lg-4 col-xs-12" >
			<label style='color:#22C7FC;font-weight:bold'>Busqueda Cliente o Factura:</label>
		<?php echo $form->textField($model,'proforma',array('style'=>'width:100%','class'=>'form-control','placeholder'=>'Ingrese Nombre o Factura')); ?></div>
		<div class="col col-lg-2 col-xs-12">
			<br>
		<?php echo CHtml::submitButton('BUSCAR', array('class'=>'btn btn-dark btn-lg btn-block')); ?>
	</div>
		<div class="col col-lg-2 col-xs-12">
			<label style='color:#22C7FC;font-weight:bold'>Fecha Desde:</label>
		<?php echo $form->textField($model,'fecha',array('type'=>'text','id'=>'fecha','class'=>'form-control','placeholder'=>date('j/n/Y'))); ?></div>
		<div class="col col-lg-2 col-xs-12">
			<label style='color:#22C7FC;font-weight:bold'>Fecha Hasta:</label><?php echo $form->textField($model,'dias',array('type'=>'text','id'=>'fecha','class'=>'form-control','placeholder'=>date('j/n/Y'))); ?></div>
			   <div class="col col-lg-2 col-xs-12 "><br>
                                <?php
                                    echo CHtml::link('<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nuevo ',array('proforma/create'),array('id'=>'bt1','class'=>"btn  btn-block btn-lg",'style'=>'background-color: #99cc33;color:white' ));
                                ?>
                             </div>
<?php $this->endWidget(); ?>
</div><br><!-- search-form -->

facturaelectronica/protected/modules/facturas/views/proforma/index.php
<?php
/* @var $this ProformaController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Proformas',
);

$this->menu=array(
	array('label'=>'Create Proforma', 'url'=>array('create')),
	array('label'=>'Manage Proforma', 'url'=>array('admin')),
);
?>

<h1>Proformas</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

facturaelectronica/protected/modules/facturas/views/proforma/view.php
<?php
/* @var $this ProformaController */
/* @var $model Proforma */

$this->breadcrumbs=array(
	'Proformas'=>array('index'),
	$model->id_proforma,
);

$this->menu=array(
	array('label'=>'List Proforma', 'url'=>array('index')),
	array('label'=>'Create Proforma', 'url'=>array('create')),
	array('label'=>'Update Proforma', 'url'=>array('update', 'id'=>$model->id_proforma)),
	array('label'=>'Delete Proforma', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id_proforma),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Proforma', 'url'=>array('admin')),
);
?>

<h1>View Proforma #<?php echo $model->id_proforma; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id_proforma',
		'proforma',
		'id_cliente',
		'id_moneda',
		'fecha',
		'id_codigo_producto',
		'dias',
		'cantidad',
		'id_descuento',
		'total',
		'iv',
		'otros_impuestos_id',
		'observaciones',
		'nombre_cliente',
		'id_articulo',
		'precio_aimpu',
		'subtotal',
		'total2',
		'descuento2',
		'credito',
		'efec_monto',
		'tj_nm',
		'tj_ref',
		'tj_monto',
		'ch_bnc',
		'ch_ref',
		'ch_monto',
		'trs_bnc',
		'trs_ref',
		'trs_monto',
		'ot_ref',
		'ot_monto',
		'total_payment',
		'total_completo',
		'vuelto',
		'contingencia',
		'tipoexoneracion',
		'documentoexo',
		'instituexo',
		'fechaexo',
		'impuestoexo',
		'porcentajeexo',
		'n_conting',
		'fecha_conting',
		'razon_cont',
	),
)); ?>